### PR TITLE
fix(gitinterface): parse renamed entries in status output

### LINKED ISSUE #1272: pkg/gitinterface: Status() fails for renamed files (missing 'R' status parsing)
### Description
`Repository.Status()` fails when a file is renamed (`git mv`), because the status parser does not recognize the `'R'` porcelain status code.

### Steps to Reproduce
1. Create a repo and commit `old.txt`.
2. Rename it to `new.txt` using `git mv old.txt new.txt`.
3. Call `repo.Status()` from `pkg/gitinterface`.

### Actual Result
`repo.Status()` returns:
`unable to parse status code 'R' for path 'new.txt': status code string is unrecognized`

### Expected Result
`repo.Status()` should parse renamed-file status correctly and return a valid `FileStatus` map without error.

### Why this is a bug
- The status enum includes `StatusCodeRenamed`, but the parser (`NewStatusCodeFromByte`) does not handle `'R'`.
- This causes valid Git porcelain output to fail parsing.

### Impact
Any feature that depends on `Repository.Status()` can break on staged renames.

### Suggested Fix
- Add `'R'` handling in `NewStatusCodeFromByte`.
- Add a regression test in `pkg/gitinterface/status_test.go` for `git mv` rename cases.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ayuxsh009**
## Description

Fixes #1272 a bug in `pkg/gitinterface.Repository.Status()` where renamed files (`git mv`) caused parsing failures.

### What changed
- Added support for `'R'` in `NewStatusCodeFromByte`.
- Updated porcelain `--porcelain=1 -z` parsing to correctly handle rename/copy records that include an extra NUL-separated source path token.
- Added regression test `TestStatusWithRenamedFile` in `pkg/gitinterface/status_test.go`.

### Verification
I manually tested and verified:
- `go test ./pkg/gitinterface -run TestStatusWithRenamedFile -v`
- `go test ./pkg/gitinterface`
- `go test ./internal/luasandbox`
- Manual rename reproduction (`git mv old.txt new.txt`) now returns parsed status without error.

## AI Usage

- [ ] I **did not** use generative AI at all in making the content of this pull
  request.
- [x] I **did** use generative AI in some form in making the content of this
  pull request. I have described my use of AI below.

Used AI minimally for wording/help drafting.  
Code changes, review, and testing were done manually and verified by me.

## Contributor Checklist

- [x] I **have manually reviewed all content** submitted to gittuf in this pull
  request.
- [x] I fully understand the content I am submitting.
- [x] The changes introduced are documented and have tests included if
  applicable.
- [x] My changes do not infringe on copyright/trademarks/etc.
- [x] All commits in this pull request include a [DCO
  Signoff](https://wiki.linuxfoundation.org/dco).
- [x] By submitting this pull request, I agree to follow the gittuf [Code of
  Conduct](https://github.com/gittuf/community/blob/main/CODE-OF-CONDUCT.md).

### CODE REVIEW

File: pkg/gitinterface/status_test.go [hunk 1]
```diff
@@ -139,3 +139,38 @@ func TestStatus(t *testing.T) {
 	assert.Nil(t, err)
 	assert.Empty(t, statuses)
 }
+
+func TestStatusWithRenamedFile(t *testing.T) {
```
Comment (patzielinski) [inline pkg/gitinterface/status_test.go]: Please integrate this test into the `TestStatus` function above. You can likely just add it to the end and move one of the existing files.

**Review by patzielinski — CHANGES_REQUESTED** [review]
cc @adityasaky for further review.

File: pkg/gitinterface/status_test.go (hunk 1 above)
Comment (ayuxsh009) [reply pkg/gitinterface/status_test.go]: Made the changes as suggested - moved the rename case into TestStatus and removed the separate test. I reused an existing tracked file for the rename to keep it consistent with the rest of the test.

Re-ran `go test ./pkg/gitinterface -run TestStatus -count=1 -v` and `go test ./pkg/gitinterface -count=1`; both are passing.

File: pkg/gitinterface/status.go [hunk 2]
```diff
@@ -115,10 +117,14 @@ func (r *Repository) Status() (map[string]FileStatus, error) {
...
 	lines := strings.Split(output, string('\000'))
-	for _, line := range lines {
+	for i := 0; i < len(lines); i++ {
+		line := lines[i]
 		if len(line) == 0 {
 			continue
 		}
+		if len(line) < 3 {
+			return nil, fmt.Errorf("unable to parse status entry '%s': malformed status output", line)
+		}
```
Comment (adityasaky) [inline pkg/gitinterface/status.go:127]: When can this happen?

File: pkg/gitinterface/status.go [hunk 3]
```diff
@@ -144,6 +150,16 @@ func (r *Repository) Status() (map[string]FileStatus, error) {
...
+
+		// In porcelain v1 -z mode, rename/copy records include a second NUL
+		// terminated path token that points to the source path.
+		if xStatus == StatusCodeRenamed || xStatus == StatusCodeCopied ||
+			yStatus == StatusCodeRenamed || yStatus == StatusCodeCopied {
+			if i+1 >= len(lines) || len(lines[i+1]) == 0 {
+				return nil, fmt.Errorf("unable to parse rename/copy status for path '%s': missing source path", filePath)
+			}
+			i++
+		}
```
Comment (adityasaky) [inline pkg/gitinterface/status.go:162]: I'm a little confused by this, and it's possible I need to refresh my memory with this bit of gitinterface. Why are we looking at subsequent lines?

**Review by adityasaky — COMMENTED** [review]
Thanks for filing this and apologies for the delay with my review.

File: pkg/gitinterface/status.go (hunk 2 above)
Comment (ayuxsh009) [reply pkg/gitinterface/status.go]: This check was intended as a defensive safeguard against malformed or unexpected output. However, since git status --porcelain=1 -z guarantees the structure of each entry, I have removed the length check to keep the parsing logic simpler and aligned with the expected format.

File: pkg/gitinterface/status.go (hunk 3 above)
Comment (ayuxsh009) [reply pkg/gitinterface/status.go]: I have clarified this in the code comments. In porcelain v1 -z mode, rename and copy entries are represented using two NUL-separated tokens - the first for the destination path and the second for the source path. Because of this, we need to look ahead and consume the next token as part of the same logical record.

**Comment by ayuxsh009** [comment]
Hi @adityasaky i have made requested changes can you please review it ?
Thanks!

File: pkg/gitinterface/status_test.go [hunk 4]
```diff
@@ -138,4 +138,16 @@ func TestStatus(t *testing.T) {
...
+	renamedPath := "baz"
+	if _, err := repo.executor("mv", filename, renamedPath).executeString(); err != nil {
+		t.Fatal(err)
+	}
+
+	statuses, err = repo.Status()
+	assert.Nil(t, err)
+	assert.Equal(t, map[string]FileStatus{
+		renamedPath: {X: StatusCodeRenamed, Y: StatusCodeUnmodified},
+	}, statuses)
```
Comment (adityasaky) [inline pkg/gitinterface/status_test.go:152]: Can you add a test case where the response has a renamed file and some other changes (e.g., added, modified, etc.)?

Comment (ayuxsh009) [reply pkg/gitinterface/status_test.go:152]: Added a test case that stages a rename (baz → quux) and an add (qux) simultaneously, then asserts both entries appear correctly in the Status() output. This verifies that the NUL-separated source-path token for the rename is properly consumed and doesn't break parsing of the following entry.

**Review by adityasaky — APPROVED** [review]

**Review by patzielinski — APPROVED** [review]
