### PR TITLE
transport: Check for empty list for-push result

### LINKED ISSUE #674: transport: Incorrect access token causes the transport to freeze
When using the transport + authenticating with GitHub (over HTTPS), an incorrect personal access token will cause the transport to freeze without exiting.

### PR DESCRIPTION
**Pull request by patzielinski**
If the user fails to authenticate with the remote using the http helper, then `list for-push` returns nothing, which is now handled by exiting with an error.

Closes #674.

### CODE REVIEW

File: internal/git-remote-gittuf/curl.go [hunk 1]
```diff
@@ -347,6 +350,12 @@ func handleCurl(repo *gittuf.Repository, remoteName, url string) (map[string]str
 			for helperStdOutScanner.Scan() {
 				output := helperStdOutScanner.Bytes()
 
+				// If nothing is returned, the user has likely failed to
+				// authenticate with the remote
+				if len(output) == 0 {
```
Comment (adityasaky) [inline internal/git-remote-gittuf/curl.go:355]: we should test this change on windows.

Comment (adityasaky) [reply internal/git-remote-gittuf/curl.go:362]: is the single byte a newline?

**Review by adityasaky — APPROVED** [review]
