### PR TITLE
rsl/record: clarify expected Git reference argument in CLI help

### LINKED ISSUE #1262: Confusion regarding policy + RSL workflow during initial setup
### Description

Hi, I was going through the [getting-started flow](https://github.com/gittuf/gittuf/blob/main/docs/get-started.md) and ran into some confusion around the sequence of:
- policy init
- policy stage / apply
- rsl record

Specifically, I encountered errors like:
- "invalid policy state"
- "verifier's key and threshold constraints not met"
- "requested Git reference not found"

It isn't fully clear:
- when RSL entries are expected to exist
- how policy staging/applying interacts with RSL recording

Additionally, I assumed initially that `gittuf rsl record` accepted a message argument (similar to `git commit -m`), but it actually expects a reference (e.g., `main`). This wasn’t immediately obvious from the CLI usage or docs and contributed to the confusion.

This can be a misunderstanding on my side, but I wanted to confirm if I'm missing any step or if the flow could be improved for first-time users.

For reference, I’m using:
gittuf version 0.13.2-0.20260406174801-ceb392bb8385+dirty

I'll be glad to dive deeper and propose improvements once I get the intended workflow better.

### Relevant log output if the discussion pertains to existing gittuf functionality

```Shell
$ gittuf policy apply --local-only
Error: invalid policy state (is policy reference out of sync with corresponding RSL entry?)

$ gittuf policy apply --local-only
Error: staged policy is invalid: verifier's key and threshold constraints not met

$ gittuf rsl record --local-only "Initial policy setup"
Error: requested Git reference not found
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by pushkarscripts**
## Description

Currently, running a command like:
```
gittuf rsl record --local-only "Initial policy setup"
```
returns a generic error message:
```
requested Git reference not found
```

This PR improves the message by including the provided input, making it clearer that the command expects a valid Git reference (e.g., `main`, `master`) rather than a message-like argument.

This came up while following the getting-started flow, where it’s easy to assume `record` to behave similar to `git commit -m`. 
I'm also open to feedback in-case a different error style is preferred. 

Fixes: #1262 

## AI Usage

- [x] I **did not** use generative AI at all in making the content of this pull
  request.
- [ ] I **did** use generative AI in some form in making the content of this
  pull request. I have described my use of AI below.

## Contributor Checklist

- [x] I **have manually reviewed all content** submitted to gittuf in this pull
  request.
- [x] I fully understand the content I am submitting.
- [x] The changes introduced are documented and have tests included if
  applicable.
- [x] My changes do not infringe on copyright/trademarks/etc.
- [x] All commits in this pull request include a [DCO
  Signoff](https://wiki.linuxfoundation.org/dco).
- [x] By submitting this pull request, I agree to follow the gittuf [Code of
  Conduct](https://github.com/gittuf/community/blob/main/CODE-OF-CONDUCT.md).

### CODE REVIEW

**Review by patzielinski — COMMENTED** [review]
Thanks for sending this in, @pushkarscripts.

The error message about the requested Git reference not being found (`ErrReferenceNotFound`), is also used in other places throughout the codebase, so I'm wary of just replacing it here.

I suggest instead reworking this PR to update the documentation for `gittuf rsl record` in https://github.com/gittuf/gittuf/blob/main/internal/cmd/rsl/record/record.go so that it's clearer that `gittuf rsl record` expects a ref as an argument.

**Comment by pushkarscripts** [comment]
> Thanks for sending this in, @pushkarscripts.
> 
> The error message about the requested Git reference not being found (`ErrReferenceNotFound`), is also used in other places throughout the codebase, so I'm wary of just replacing it here.
> 
> I suggest instead reworking this PR to update the documentation for `gittuf rsl record` in https://github.com/gittuf/gittuf/blob/main/internal/cmd/rsl/record/record.go so that it's clearer that `gittuf rsl record` expects a ref as an argument.

Thanks, that makes sense about reusing `ErrReferenceNotFound`.
I’ve updated the PR to clarify in the `gittuf rsl record` help text that it expects a Git reference (not a message).

Let me know if this looks better.

File: internal/cmd/rsl/record/record.go [hunk 1]
```diff
@@ -72,9 +72,15 @@ func (o *options) Run(cmd *cobra.Command, args []string) error {
...
-		Long:              "The 'record' command records the latest state of a Git reference in the repository's RSL. It is used to capture and track changes to references over time for auditing and consistency.",
+		Use:   "record",
+		Short: "Record latest state of a Git reference (e.g., 'main') in the RSL",
+		Long: `The 'record' command records the latest state of a Git reference in the repository's RSL.
+
+The argument must be a valid Git reference (such as 'main', 'HEAD', or a tag name), not a message.
+For example:
+  gittuf rsl record --local-only main
+
+This command is used to capture and track changes to references over time for auditing and consistency.`,
```
Comment (patzielinski) [inline internal/cmd/rsl/record/record.go]:
```suggestion
		Long: `The 'record' command records the latest state of a Git reference in the repository's RSL. The argument must be a valid Git reference (such as 'main', 'HEAD', or a tag name). For example: 'gittuf rsl record --local-only main'. This command is used to capture and track changes to references over time for auditing and consistency.`,
```
I think the first part of the explanation suffices. Please also merge the lines to be just one line.

**Review by patzielinski — COMMENTED** [review]
I've made a content suggestion. Please also ensure that you run `gofmt` on the file, as the existing formatting (i.e. all strings start at the same column) was removed.

Please also run `make generate` when you apply the changes, and add the updated Markdown file to your PR. Thanks!

**Comment by pushkarscripts** [comment]
> I've made a content suggestion. Please also ensure that you run `gofmt` on the file, as the existing formatting (i.e. all strings start at the same column) was removed.
> 
> Please also run `make generate` when you apply the changes, and add the updated Markdown file to your PR. Thanks!

Thanks! I’ve applied the suggested change, ran `gofmt` and `make generate`, and pushed the updates.

Let me know if anything else needs tweaking.

**Review by patzielinski — APPROVED** [review]
Thanks!

**Review by patzielinski — APPROVED** [review]
