### PR TITLE
Fix RSL terminology

### LINKED ISSUE #130: Settle terminology for RSL entries
The RSL can store two types of objects: an entry and an annotation. Unfortunately, we use the word "entry" in an abstract sense to refer to either of those two types. Some examples:
* the `EntryType` interface
* `GetEntry` which returns the object in the RSL for the specified ID, so this can be either an `Entry` or an `Annotation`
* other APIs

I suggest we use the word "record", possibly as a replacement for the abstract use of the word "entry". I can also see an argument to swap them around, where "entry" is generic and the type that has a ref and target ID becomes a "record". Once this terminology is settled, it should be a fairly easy, if noisy, PR to rename the corresponding APIs. The specification can also be updated at the same time to reflect the change, I foresee a smaller diff there.

### PR DESCRIPTION
**Pull request by adityasaky**
Closes #130

Renames:
Entry -> ~StandardEntry~ ReferenceEntry
Annotation -> AnnotationEntry
EntryType -> Entry

Some APIs like GetEntry... have been renamed depending on whether they return a standard entry or a generic entry.

### CODE REVIEW

File: internal/policy/policy.go [hunk 1]
```diff
@@ -84,7 +84,7 @@ type State struct {
 // LoadState returns the State of the repository's policy corresponding to the
 // rslEntryID.
 func LoadState(ctx context.Context, repo *git.Repository, rslEntryID plumbing.Hash) (*State, error) {
-	e, err := rsl.GetEntry(repo, rslEntryID)
+	e, err := rsl.GetItem(repo, rslEntryID)
```
Comment (JustinCappos) [inline internal/policy/policy.go:87]: Are an Entry and an EntryType the same?!?  They both got replaced with "Item"...

File: internal/policy/verify.go [hunk 2]
```diff
@@ -53,7 +53,7 @@ func VerifyRef(ctx context.Context, repo *git.Repository, target string) error {
 	}
 
 	// 2. Find latest entry for target
-	latestEntry, err := rsl.GetLatestEntryForRef(repo, target)
+	latestEntry, _, err := rsl.GetLatestEntryForRef(repo, target)
```
Comment (JustinCappos) [inline internal/policy/verify.go:56]: These still use Entry...

**Review by JustinCappos — COMMENTED** [review]
I know this is a draft PR.  I'm quite confused overall about the change and wanted to raise this confusion sooner rather than later.  I'm happy to discuss...

File: internal/policy/policy.go (hunk 1 above)
Comment (adityasaky) [reply internal/policy/policy.go:87]: No, they're not, this is fixing an earlier mistake. EntryType was supposed to be the generic type, representative of both Entry and Annotation. That's now replaced by Item. GetEntry was named incorrectly, because it can return either an Entry or an Annotation depending on what's requested. So GetEntry becomes GetItem.

File: internal/policy/verify.go (hunk 2 above)
Comment (adityasaky) [reply internal/policy/verify.go:56]: In this case, this is supposed to return an Entry and never an Annotation. So this is a correct use of "Entry".

File: internal/policy/policy.go (hunk 1 above)
Comment (adityasaky) [reply internal/policy/policy.go:87]: To summarize, this PR:
* renames EntryType to Item to avoid collision with Entry
* fixes some APIs that used Entry in the name when in fact they return an Item, previously EntryType

Comment (adityasaky) [reply internal/policy/policy.go:87]: Also note that only the last commit pertains to the terminology. I built this PR off the commits from #129, I'll rebase once that one's merged but doing it this way avoids some conflicts. This is also why it's still a draft.

File: internal/rsl/rsl.go [hunk 3]
```diff
@@ -77,34 +80,38 @@ type Entry struct {
 	TargetID plumbing.Hash
 }
 
-// NewEntry returns an Entry object for a normal RSL entry.
-func NewEntry(refName string, targetID plumbing.Hash) *Entry {
-	return &Entry{RefName: refName, TargetID: targetID}
+// NewStandardEntry returns a StandardEntry object for a normal RSL entry.
+func NewStandardEntry(refName string, targetID plumbing.Hash) *StandardEntry {
```
Comment (wlynch) [inline internal/rsl/rsl.go:84]: bikeshedding a little bit here since we're renaming anyway: If it's not a StandardEntry, does that make anything else a non-standard Entry? 🤔 

Should this be a `ReferenceEntry` / `ReferenceStateEntry` / something else?

Comment (adityasaky) [reply internal/rsl/rsl.go:84]: Fair point, I like ReferenceEntry the best. I can submit it fairly quickly.

Comment (adityasaky) [reply internal/rsl/rsl.go]: Done!

**Review by wlynch — APPROVED** [review]
